### ISSUE TITLE
_pickle.PicklingError on Pythonista 3

### ISSUE THREAD

**Issue by cclauss** [oreilly-japan/deep-learning-from-scratch#15]
http://omz-software.com/pythonista/  Python 3.5.1 and NumPy 1.8.0

```
Downloading t10k-labels-idx1-ubyte.gz ... 
Done
Downloading train-labels-idx1-ubyte.gz ... 
Done
Downloading t10k-images-idx3-ubyte.gz ... 
Done
Downloading train-images-idx3-ubyte.gz ... 
Done
Converting train-images-idx3-ubyte.gz to NumPy Array ...
Done
Converting train-labels-idx1-ubyte.gz to NumPy Array ...
Done
Converting t10k-images-idx3-ubyte.gz to NumPy Array ...
Done
Converting t10k-labels-idx1-ubyte.gz to NumPy Array ...
Done
Creating pickle file ...
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/C2DC6C38-3D98-4394-B761-B6CA01482067/Pythonista3/Documents/from GitHub/deep-learning-from-scratch-master/dataset/mnist.py", line 128, in <module>
    init_mnist()
  File "/private/var/mobile/Containers/Shared/AppGroup/C2DC6C38-3D98-4394-B761-B6CA01482067/Pythonista3/Documents/from GitHub/deep-learning-from-scratch-master/dataset/mnist.py", line 79, in init_mnist
    pickle.dump(dataset, f, -1)
_pickle.PicklingError: Can't pickle <built-in function _reconstruct>: import of module 'multiarray' failed

---

>>> import platform
>>> platform.python_version()
'3.5.1'
>>> import numpy
>>> numpy.__version__
'1.8.0'
```

**Comment by cclauss** [comment]
https://github.com/omz/Pythonista-Issues/issues/260 Is the problem.
