### ISSUE TITLE
解決方法：MNISTデータがHTTP Error 403: Forbiddenで読み込めない

### ISSUE THREAD

**Issue by matsuda-tkm** [oreilly-japan/deep-learning-from-scratch#81]
## 実行環境

> - OS：macOS Sonoma 14.4.1
> - Python：3.12.3
> - パッケージ管理：Poetry
> - 入っているライブラリ（`poetry show`の結果）
>     - contourpy       1.2.1
>     - cycler          0.12.1
>     - fonttools       4.51.0
>     - kiwisolver      1.4.5
>     - matplotlib      3.8.4
>     - numpy           1.26.4
>     - packaging       24.0
>     - pillow          10.3.0
>     - pyparsing       3.1.2
>     - python-dateutil 2.9.0.post0
>     - six             1.16.0

## 問題の事象
[ch03/neuralnet_mnist.py](https://github.com/oreilly-japan/deep-learning-from-scratch/blob/01dd7a0ad931a034d0dfb6dd8284af5706ad01e4/ch03/neuralnet_mnist.py)を実行したところ、以下のように`urllib.error.HTTPError: HTTP Error 403: Forbidden`というエラーが発生し、MNISTデータをダウンロードできない。

```
Downloading train-images-idx3-ubyte.gz ... 
Traceback (most recent call last):
  File "/Users/takumi/github/deep-learning-from-scratch/ch03/neuralnet_mnist.py", line 35, in <module>
    x, t = get_data()
           ^^^^^^^^^^
  File "/Users/takumi/github/deep-learning-from-scratch/ch03/neuralnet_mnist.py", line 11, in get_data
    (x_train, t_train), (x_test, t_test) = load_mnist(normalize=True, flatten=True, one_hot_label=False)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/takumi/github/deep-learning-from-scratch/ch03/../dataset/mnist.py", line 111, in load_mnist
    init_mnist()
  File "/Users/takumi/github/deep-learning-from-scratch/ch03/../dataset/mnist.py", line 80, in init_mnist
    download_mnist()
  File "/Users/takumi/github/deep-learning-from-scratch/ch03/../dataset/mnist.py", line 47, in download_mnist
    _download(v)
  File "/Users/takumi/github/deep-learning-from-scratch/ch03/../dataset/mnist.py", line 40, in _download
    response = urllib.request.urlopen(request).read()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

## 解決方法
- [dataset/mnist.py](https://github.com/oreilly-japan/deep-learning-from-scratch/blob/f549a1886b4c03a252ac7549311e29c1ed78a8a1/dataset/mnist.py)の13行目を以下のように変更する。
- 変更前
```python
url_base = 'http://yann.lecun.com/exdb/mnist/'
```
- 変更後
```python
url_base = 'https://storage.googleapis.com/cvdf-datasets/mnist/'
```

## 解決にあたって参考にしたもの
- https://github.com/cvdfoundation/mnist?tab=readme-ov-file#download
    - READMEの[Training images](https://storage.googleapis.com/cvdf-datasets/mnist/train-images-idx3-ubyte.gz), [Training labels](https://storage.googleapis.com/cvdf-datasets/mnist/train-labels-idx1-ubyte.gz), [Testing images ](https://storage.googleapis.com/cvdf-datasets/mnist/t10k-images-idx3-ubyte.gz), [Testing labels](https://storage.googleapis.com/cvdf-datasets/mnist/t10k-labels-idx1-ubyte.gz)に張られたリンク先からダウンロードすればよい

**Comment by koki0702** [comment]
本家URLが403になっていたので、ミラーサイトに変更しました。
（PyTorchのコードを参考にしました）

https://github.com/oreilly-japan/deep-learning-from-scratch/commit/497a4ac8859dce7a3b4819edf695364afe73fcda
